// requires: App.ui.styles.theme
'use strict';
App.ui = App.ui || {};
App.ui.styles = App.ui.styles || {};
// The compact bar's per-contact task list (src/ui/compactContactTasks.js) — deliberately minimal
// (complete button, title, due date only), a hairline-separated column that sits below the compact
// bar's own header/quick-add rows, inside the same `.crmtm-compact-bar` element so it scrolls/drags
// with the bar as one unit (see src/ui/styles/shell.js's `.crmtm-compact-bar`).
App.ui.styles.compactContactTasks = [
  '.crmtm-cct { display: flex; flex-direction: column; gap: 2px; border-top: 1px solid var(--crmtm-border); padding-top: 6px; max-height: 160px; overflow-y: auto; }',
  '',
  '.crmtm-cct-row { display: flex; align-items: center; gap: 8px; padding: 3px 0; }',
  '',
  '.crmtm-cct-complete {',
  '  background: none; border: 1px solid var(--crmtm-border); color: var(--crmtm-success);',
  '  border-radius: 50%; width: 18px; height: 18px; min-width: 18px; font-size: 11px; cursor: pointer;',
  '  display: flex; align-items: center; justify-content: center; flex-shrink: 0;',
  '}',
  '.crmtm-cct-complete:hover { background: var(--crmtm-bg-hover); }',
  '.crmtm-cct-complete:disabled { opacity: 0.5; cursor: default; }',
  '',
  '.crmtm-cct-title {',
  '  flex: 1; min-width: 0; font-size: 12px; color: var(--crmtm-text); white-space: nowrap;',
  '  overflow: hidden; text-overflow: ellipsis;',
  '}',
  '',
  '.crmtm-cct-due { font-size: 11px; color: var(--crmtm-text-muted); flex-shrink: 0; white-space: nowrap; }',
  '',
  '.crmtm-cct-error { font-size: 11px; color: var(--crmtm-danger); padding: 2px 0; }',
  '',
  '.crmtm-cct-banner {',
  '  display: flex; align-items: center; gap: 8px; font-size: 11px; color: var(--crmtm-text-muted);',
  '  padding: 2px 0; flex-wrap: wrap;',
  '}',
  // .crmtm-btn defaults to a fixed 26x26 icon-button square (see styles/shell.js) — every text button
  // in this app overrides width/height to auto, same as .crmtm-settings-save/.crmtm-tep-save do.
  '.crmtm-cct-map-btn { width: auto; height: auto; font-size: 11px; padding: 2px 8px; }',
  '',
  // The debug details disclosure (map/remap and offer-to-create banners) — a small chevron that rotates
  // open, and a hairline-bordered panel of raw extracted values / Notion query results below the banner.
  '.crmtm-cct-details-toggle {',
  '  background: none; border: none; color: var(--crmtm-text-tertiary); cursor: pointer;',
  '  width: auto; height: auto; padding: 2px; display: flex; align-items: center; justify-content: center;',
  '  flex-shrink: 0; margin-left: auto; transition: transform 0.12s ease;',
  '}',
  '.crmtm-cct-details-toggle:hover { color: var(--crmtm-text-muted); }',
  '.crmtm-cct-details-toggle-open { transform: rotate(180deg); }',
  '',
  '.crmtm-cct-details-panel {',
  '  border: 1px solid var(--crmtm-border); border-radius: var(--crmtm-radius-sm); background: var(--crmtm-bg-hover);',
  '  padding: 6px 8px; margin: 2px 0 6px; font-size: 11px; color: var(--crmtm-text-muted);',
  '  display: flex; flex-direction: column; gap: 3px; max-height: 220px; overflow-y: auto;',
  '}',
  '',
  '.crmtm-cct-details-row { display: flex; gap: 6px; }',
  '.crmtm-cct-details-label { color: var(--crmtm-text-tertiary); flex-shrink: 0; }',
  '.crmtm-cct-details-value { color: var(--crmtm-text); word-break: break-all; }',
  '',
  '.crmtm-cct-details-heading {',
  '  color: var(--crmtm-text-tertiary); text-transform: uppercase; font-size: 10px; letter-spacing: 0.03em;',
  '  margin-top: 4px;',
  '}',
  '.crmtm-cct-details-heading:first-child { margin-top: 0; }',
  '',
  '.crmtm-cct-details-empty { color: var(--crmtm-text-faint); font-style: italic; }',
  '',
  '.crmtm-cct-details-candidate { color: var(--crmtm-danger); }',
  '.crmtm-cct-details-candidate-ok { color: var(--crmtm-success); }',
  '',
  '.crmtm-cct-candidate {',
  '  display: flex; align-items: center; justify-content: space-between; gap: 6px; padding: 2px 0;',
  '}',
  '.crmtm-cct-candidate-info { color: var(--crmtm-text); overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }',
  '.crmtm-cct-candidate-use { width: auto; height: auto; font-size: 10px; padding: 1px 6px; flex-shrink: 0; }',
].join('\n');
