// requires: App.ui.styles.theme
'use strict';
App.ui = App.ui || {};
App.ui.styles = App.ui.styles || {};
// Notion-style Filter/Sort toolbar CSS (docs/notion-views-plan.md Phase C, implements
// App_Filter_Sort_UI_Spec.docx §2-§6) — every color/spacing value below maps to a var(--crmtm-*) token
// from App.ui.styles.theme (updated 2026-08-12 to the doc's exact hex values) rather than a second
// hardcoded palette, per this project's "modularize per-feature, shared tokens in theme.js" convention.
App.ui.styles.filterSortBar = [
  '.crmtm-fsb-toolbar {',
  '  display: flex; align-items: center; gap: 8px; padding: 8px 12px; margin-bottom: 8px;',
  '  border: 1px solid var(--crmtm-border); border-radius: var(--crmtm-radius-sm); background: var(--crmtm-bg);',
  '}',
  '.crmtm-fsb-btn-wrap { position: relative; display: inline-block; }',
  '',
  '.crmtm-fsb-btn {',
  '  display: inline-flex; align-items: center; gap: 6px; height: 28px; padding: 0 10px;',
  '  border: 1px solid var(--crmtm-border); border-radius: var(--crmtm-radius-sm); background: var(--crmtm-bg);',
  '  color: var(--crmtm-text); font: 500 13px inherit; cursor: pointer;',
  '}',
  '.crmtm-fsb-btn:hover { background: var(--crmtm-bg-hover); border-color: var(--crmtm-border-hover); }',
  '.crmtm-fsb-btn:focus-visible { box-shadow: 0 0 0 3px rgba(47,111,237,0.15); outline: none; }',
  '.crmtm-fsb-btn.is-active {',
  '  background: var(--crmtm-accent-bg); border-color: var(--crmtm-accent-border); color: var(--crmtm-accent);',
  '}',
  '.crmtm-fsb-btn-icon { display: flex; }',
  '.crmtm-fsb-btn-icon svg { display: block; }',
  '.crmtm-fsb-badge {',
  '  display: inline-flex; align-items: center; justify-content: center; min-width: 16px; height: 16px;',
  '  padding: 0 4px; margin-left: 4px; border-radius: 8px; background: var(--crmtm-accent); color: #fff;',
  '  font-size: 10px; font-weight: 700;',
  '}',
  '',
  '.crmtm-fsb-panel {',
  '  position: absolute; top: calc(100% + 8px); left: 0; width: 344px; max-height: 70vh; overflow-y: auto;',
  '  background: var(--crmtm-bg-raised); border-radius: var(--crmtm-radius); box-shadow: var(--crmtm-shadow);',
  '  padding: 6px; z-index: 30;',
  '}',
  '.crmtm-fsb-panel[hidden] { display: none; }',
  '',
  '.crmtm-fsb-picker-anchor { position: relative; display: inline-block; }',
  '.crmtm-fsb-picker, .crmtm-fsb-condmenu {',
  '  position: absolute; top: calc(100% + 4px); left: 0; background: var(--crmtm-bg-raised);',
  '  border-radius: var(--crmtm-radius); box-shadow: var(--crmtm-shadow); z-index: 40;',
  '}',
  '.crmtm-fsb-picker { width: 260px; padding: 6px; }',
  '.crmtm-fsb-condmenu { width: 176px; padding: 4px; }',
  '',
  '.crmtm-fsb-picker-search {',
  '  display: flex; align-items: center; gap: 6px; height: 30px; padding: 0 8px; margin: 2px 0 6px;',
  '  border-bottom: 1px solid var(--crmtm-border);',
  '}',
  '.crmtm-fsb-picker-search-icon { display: flex; color: var(--crmtm-text-tertiary); }',
  '.crmtm-fsb-picker-input {',
  '  flex: 1; border: none; outline: none; font-size: 12.5px; color: var(--crmtm-text); background: none;',
  '}',
  '.crmtm-fsb-picker-input::placeholder { color: var(--crmtm-text-tertiary); }',
  '',
  '.crmtm-fsb-picker-list { display: flex; flex-direction: column; gap: 1px; max-height: 220px; overflow-y: auto; }',
  '.crmtm-fsb-picker-empty { padding: 8px; font-size: 12.5px; color: var(--crmtm-text-tertiary); }',
  '.crmtm-fsb-picker-row {',
  '  display: flex; align-items: center; gap: 9px; height: 32px; padding: 0 8px; border-radius: var(--crmtm-radius-sm);',
  '  background: none; border: none; width: 100%; cursor: pointer; text-align: left;',
  '}',
  '.crmtm-fsb-picker-row:hover, .crmtm-fsb-picker-row:focus-visible { background: var(--crmtm-bg-hover); outline: none; }',
  '.crmtm-fsb-picker-row-icon { display: flex; flex-shrink: 0; color: var(--crmtm-text-muted); }',
  '.crmtm-fsb-picker-row-name { flex: 1; font-size: 13px; font-weight: 500; color: var(--crmtm-text); }',
  '.crmtm-fsb-picker-row-hint { font-size: 11px; color: var(--crmtm-text-tertiary); }',
  '',
  '.crmtm-fsb-condmenu-row {',
  '  display: flex; align-items: center; justify-content: space-between; height: 28px; padding: 0 8px;',
  '  border-radius: 5px; background: none; border: none; width: 100%; cursor: pointer; text-align: left;',
  '  font-size: 12.5px; color: var(--crmtm-text);',
  '}',
  '.crmtm-fsb-condmenu-row:hover { background: var(--crmtm-bg-hover); }',
  '.crmtm-fsb-condmenu-row.is-selected { background: var(--crmtm-accent-bg); color: var(--crmtm-accent); font-weight: 600; }',
  '.crmtm-fsb-condmenu-check { display: flex; color: var(--crmtm-accent); }',
  '',
  '.crmtm-fsb-row {',
  '  display: flex; align-items: center; gap: 4px; height: 28px; padding: 4px 0; position: relative;',
  '}',
  '.crmtm-fsb-chip-wrap { position: relative; flex-shrink: 0; }',
  '.crmtm-fsb-prop-chip, .crmtm-fsb-cond-chip {',
  '  display: flex; align-items: center; gap: 6px; height: 28px; padding: 0 8px; border-radius: var(--crmtm-radius-sm);',
  '  border: 1px solid var(--crmtm-border); font-size: 13px; font-weight: 500; color: var(--crmtm-text-muted);',
  '  white-space: nowrap; background: var(--crmtm-bg);',
  '}',
  '.crmtm-fsb-prop-chip { cursor: default; }',
  '.crmtm-fsb-prop-chip-clickable { cursor: pointer; }',
  '.crmtm-fsb-prop-chip-clickable:hover { background: var(--crmtm-bg-hover); }',
  '.crmtm-fsb-cond-chip { cursor: pointer; color: var(--crmtm-text); }',
  '.crmtm-fsb-cond-chip:hover { background: var(--crmtm-bg-hover); }',
  '.crmtm-fsb-chip-icon { display: flex; flex-shrink: 0; }',
  '.crmtm-fsb-chip-chevron { display: flex; color: var(--crmtm-text-tertiary); }',
  '',
  '.crmtm-fsb-value-wrap { flex: 1; min-width: 104px; }',
  '.crmtm-fsb-value-input, .crmtm-fsb-value-select {',
  '  width: 100%; height: 28px; padding: 0 8px; border: 1px solid var(--crmtm-border); border-radius: var(--crmtm-radius-sm);',
  '  font-size: 12.5px; color: var(--crmtm-text); background: var(--crmtm-bg); box-sizing: border-box;',
  '}',
  '.crmtm-fsb-value-input:focus, .crmtm-fsb-value-select:focus {',
  '  outline: none; border-color: var(--crmtm-accent); box-shadow: 0 0 0 3px rgba(47,111,237,0.15);',
  '}',
  '.crmtm-fsb-date-value .crmtm-flyout-trigger { width: 100%; box-sizing: border-box; }',
  '',
  '.crmtm-fsb-remove {',
  '  display: flex; align-items: center; justify-content: center; width: 24px; height: 24px; flex-shrink: 0;',
  '  border-radius: 5px; border: none; background: none; color: var(--crmtm-text-tertiary); cursor: pointer;',
  '}',
  '.crmtm-fsb-remove:hover { background: var(--crmtm-bg-hover); color: var(--crmtm-danger); }',
  '',
  '.crmtm-fsb-divider { display: flex; align-items: center; gap: 8px; padding: 2px 0; }',
  '.crmtm-fsb-divider-label {',
  '  border: none; background: none; padding: 0; font-size: 10.5px; font-weight: 700; letter-spacing: 0.03em;',
  '  text-transform: uppercase; color: var(--crmtm-accent); cursor: pointer;',
  '}',
  '.crmtm-fsb-divider-rule { flex: 1; height: 1px; background: var(--crmtm-border); }',
  '',
  '.crmtm-fsb-group {',
  '  margin: 4px 0; padding: 6px; border: 1px solid var(--crmtm-border); border-radius: var(--crmtm-radius-sm);',
  '  background: var(--crmtm-bg-hover);',
  '}',
  '.crmtm-fsb-group-header { display: flex; align-items: center; justify-content: space-between; padding: 0 2px 4px; }',
  '.crmtm-fsb-group-label { font-size: 11px; font-weight: 700; text-transform: uppercase; color: var(--crmtm-text-tertiary); }',
  '.crmtm-fsb-group-body .crmtm-fsb-group { background: var(--crmtm-bg); }',
  '',
  '.crmtm-fsb-add-row { display: flex; align-items: center; gap: 8px; padding-top: 2px; }',
  '.crmtm-fsb-add-btn {',
  '  display: inline-flex; align-items: center; gap: 6px; height: 30px; padding: 0 8px; border-radius: var(--crmtm-radius-sm);',
  '  border: none; background: none; font-size: 13px; font-weight: 500; color: var(--crmtm-text-muted); cursor: pointer;',
  '}',
  '.crmtm-fsb-add-btn:hover { background: var(--crmtm-bg-hover); color: var(--crmtm-text); }',
  '.crmtm-fsb-add-icon { display: flex; }',
  '',
  '.crmtm-fsb-sort-list { display: flex; flex-direction: column; gap: 4px; }',
  '.crmtm-fsb-sort-row.is-dragging { opacity: 0.6; }',
  '.crmtm-fsb-sort-row .crmtm-fsb-prop-chip-clickable { cursor: grab; }',
  '',
  '.crmtm-fsb-direction-toggle {',
  '  display: flex; height: 28px; border: 1px solid var(--crmtm-border); border-radius: var(--crmtm-radius-sm);',
  '  overflow: hidden; flex-shrink: 0;',
  '}',
  '.crmtm-fsb-direction-seg {',
  '  padding: 0 10px; border: none; border-right: 1px solid var(--crmtm-border); background: none;',
  '  font-size: 12.5px; color: var(--crmtm-text-muted); cursor: pointer;',
  '}',
  '.crmtm-fsb-direction-seg:last-child { border-right: none; }',
  '.crmtm-fsb-direction-seg.is-selected { background: var(--crmtm-accent-bg); color: var(--crmtm-accent); font-weight: 600; }',
].join('\n');
