// requires: App.ui.styles.theme
'use strict';
App.ui = App.ui || {};
App.ui.styles = App.ui.styles || {};
// The Notion-style task-edit side panel (src/ui/taskEditPanel.js): a fixed, full-height overlay that
// slides a fixed-width panel in from the right over whatever full-screen view is currently showing.
App.ui.styles.taskEditPanel = [
  '.crmtm-tep-overlay {',
  '  position: fixed; inset: 0; background: rgba(15,15,15,0.35); z-index: 2147483100;',
  '  display: flex; justify-content: flex-end; opacity: 0; pointer-events: none;',
  '  transition: opacity 0.15s ease;',
  '}',
  '.crmtm-tep-overlay.is-open { opacity: 1; pointer-events: auto; }',
  '',
  '.crmtm-tep-panel {',
  '  width: 380px; max-width: 92vw; height: 100%; background: var(--crmtm-bg); color: var(--crmtm-text);',
  '  box-shadow: var(--crmtm-shadow); display: flex; flex-direction: column; padding: 18px;',
  '  gap: 12px; overflow-y: auto; transform: translateX(24px); transition: transform 0.15s ease;',
  '}',
  '.crmtm-tep-overlay.is-open .crmtm-tep-panel { transform: translateX(0); }',
  '',
  '.crmtm-tep-header { display: flex; align-items: center; justify-content: space-between; gap: 8px; }',
  '.crmtm-tep-contact {',
  '  background: none; border: none; color: var(--crmtm-accent); font-size: 13px; font-weight: 600;',
  '  cursor: pointer; text-align: left; padding: 0; min-width: 0; overflow: hidden; text-overflow: ellipsis;',
  '  white-space: nowrap;',
  '}',
  '.crmtm-tep-contact:hover { text-decoration: underline; }',
  '.crmtm-tep-close {',
  '  background: none; border: none; color: var(--crmtm-text-faint); font-size: 18px; cursor: pointer;',
  '  width: 26px; height: 26px; border-radius: var(--crmtm-radius-sm); flex-shrink: 0;',
  '}',
  '.crmtm-tep-close:hover { background: var(--crmtm-bg-hover); color: var(--crmtm-text); }',
  '',
  '.crmtm-tep-field { display: flex; flex-direction: column; gap: 4px; }',
  '.crmtm-tep-label { font-size: 11px; color: var(--crmtm-text-muted); text-transform: uppercase; letter-spacing: 0.02em; }',
  '.crmtm-tep-note {',
  '  border: 1px solid var(--crmtm-border); border-radius: var(--crmtm-radius-sm); padding: 6px 8px;',
  '  font-size: 13px; color: var(--crmtm-text); background: var(--crmtm-bg);',
  '}',
  '.crmtm-tep-completed { display: flex; align-items: center; gap: 8px; font-size: 13px; cursor: pointer; }',
  '.crmtm-tep-title { font-size: 11px; color: var(--crmtm-text-muted); }',
  '.crmtm-tep-error { color: var(--crmtm-danger); font-size: 11px; }',
  '',
  '.crmtm-tep-actions { display: flex; align-items: center; gap: 8px; margin-top: auto; padding-top: 8px; }',
  '.crmtm-tep-save { width: auto; padding: 0 14px; background: var(--crmtm-accent); color: #fff; }',
  '.crmtm-tep-save:hover { background: var(--crmtm-accent); opacity: 0.9; }',
  '.crmtm-tep-cancel { width: auto; padding: 0 14px; }',
  '.crmtm-tep-delete {',
  '  width: auto; padding: 0 10px; margin-left: auto; background: var(--crmtm-danger-bg);',
  '  color: var(--crmtm-danger);',
  '}',
  '.crmtm-tep-delete:hover { background: var(--crmtm-danger); color: #fff; }',
  '.crmtm-tep-delete:disabled { opacity: 0.5; cursor: default; }',
].join('\n');
